services:
  engine:
    container_name: sebas.tech-engine
    build:
      context: ./engine
      dockerfile: Dockerfile
    env_file:
      - ./engine/.env
    ports:
      - "5002:5002"
    volumes:
      - ./engine:/usr/src/app
      - ./engine/package.json:/usr/src/app/package.json
      - ./engine/package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - network

  database:
    image: mysql:8
    container_name: sebas.tech-database
    restart: unless-stopped
    tty: true
    env_file:
      - .env.database
    ports:
      - "3308:3308"
    expose:
      - 3308
    volumes:
      - database_volume:/var/lib/mysql/
    networks:
      - network

  adminer:
    image: adminer
    container_name: sebas.tech-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_volume:
